cost:
  dreaming_z_reg: 0.1
  gamma: 0.99
  lambda_a: 0.0
  lambda_j: 0.0
  lambda_l: 0.2
  lambda_o: 1.0
  lambda_p: 1.0
  u_hinge: 0.5
  u_reg: 0.05
  uncertainty_n_batches: 100
  uncertainty_n_models: 10
  uncertainty_n_pred: 30
model:
  checkpoint: null
  h_height: 14
  h_width: 3
  height: 117
  hidden_size: 10752
  model_type: vanilla_v3
  n_actions: 2
  n_cond: 20
  n_feature: 256
  n_hidden: 256
  n_inputs: 4
  n_pred: 30
  turn_power: 1
  width: 24
training:
  batch_size: 10
  data_shift: false
  debug: false
  diffs: false
  distributed_backend: ddp
  epoch_size: 500
  experiment_name: vanilla_w_no_action_no_diff
  fast_dev_run: false
  freeze_encoder: false
  gpus: 1
  learning_rate: 0.0001
  mixout_p: null
  n_epochs: 100
  n_steps: 500000.0
  noise_augmentation_p: 0.0
  noise_augmentation_std: 0.07
  num_nodes: 1
  prince: false
  random_actions: false
  resume_from_checkpoint: null
  run_eval: false
  scheduler: step
  seed: 8888
  slurm: true
  slurm_constraint: turing
  validation_eval: false
  validation_period: 1
  validation_size: 25
  version: null
