model:
  beta: 1.0e-06
  checkpoint: null
  dropout: 0.1
  fm_type: km_no_action
  h_height: 14
  h_width: 3
  height: 117
  hidden_size: 10752
  huber_loss: false
  layers: 3
  model_type: fm
  n_actions: 2
  n_feature: 256
  n_hidden: 256
  n_inputs: 4
  ncond: 20
  nfeature: 256
  nz: 32
  predict_state: false
  width: 24
  z_dropout: 0.5
training:
  auto_enable_latent: false
  batch_size: 64
  data_shift: false
  debug: false
  decay: 1
  decay_period: 1
  diffs: false
  distributed_backend: ddp
  enable_latent: true
  epoch_size: 500
  fast_dev_run: false
  freeze_encoder: false
  gpus: 2
  learning_rate: 0.0001
  mixout_p: null
  n_cond: 20
  n_epochs: 938
  n_pred: 20
  n_steps: 30000000.0
  noise_augmentation_p: 0.0
  noise_augmentation_std: 0.07
  num_nodes: 1
  random_actions: false
  resume_from_checkpoint: null
  run_eval: false
  seed: 42
  slurm: true
  slurm_constraint: turing
  validation_eval: true
  validation_period: 1
  validation_size: 25
  validation_steps: 10000
  version: null
